repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # to format code
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10

  # to lint code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # to sort imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        # https://stackoverflow.com/questions/77786047/git-pre-commit-hook-isort-and-black-keep-failing-for-a-python-project
        args: ["--profile", "black"]
  # * better to run a script to run tests before committing changes, also making pre-comit checks to be fast
  # - repo: local
  #   hooks:
  #     - id: run-pytest
  #       name: Run Pytest
  #       entry: ./scripts/run_tests.sh
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
