services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:13
    environment:
      POSTGRES_DB: fastapi_todo_test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - 5434:5432

volumes:
  pg-data:
